name: Scan Secrets

on: [push]

jobs:
  gitleaks:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4  

      - name: Install Gitleaks
        run: |
          wget https://github.com/gitleaks/gitleaks/releases/latest/download/gitleaks-linux-amd64
          chmod +x gitleaks-linux-amd64
          sudo mv gitleaks-linux-amd64 /usr/local/bin/gitleaks

      - name: Verify installation
        run: gitleaks version

      - name: Run Gitleaks
        run: gitleaks detect --source . --no-git --verbose
